### ISSUE TITLE
[イベントID] フォーマットを変更する

### ISSUE THREAD

**Issue by yKicchan** [Opportunes/EvelyApi#9]
現在のフォーマット`YYYYMMDD-n`から8桁のランダムな英数字`^[a-zA-Z0-9]{8}$`に変更する

**Comment by shionfujie** [comment]
イベントIDのフォーマットは英数字にすることにしたの？

**Comment by yKicchan** [comment]
@Sunny-Moon 
そうですね、冷静に考え直した結果、連番だと欠番が出るのと、１日に２つ以上イベントを立てることがほとんどなさそうなので...

あとは19890225みたいなのが1989225に変換されてしまったり、理論上１日に10個以上の作成で桁数が変わるのもいやだなぁと。

ちなみに1989年2月25日は**花澤香菜の誕生日**ですよ。
